# Generated by Django 5.0 on 2026-07-10 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migracion_masiva_archivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucioncargamasiva',
            name='cancelacion_solicitada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConfiguracionMigracionMasivaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('correo_destino', models.EmailField(blank=True, max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_migracion_masiva_archivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion Migracion Masiva de Archivo',
                'verbose_name_plural': 'Configuraciones Migracion Masiva de Archivo',
                'db_table': 'migracion_masiva_archivo_configuracion',
            },
        ),
    ]
