# Generated by Django 5.0 on 2026-07-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migracion_masiva_archivo', '0002_ejecucioncargamasiva_cancelacion_solicitada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotedocumental',
            options={'ordering': ['-creado'], 'verbose_name': 'Lote documental', 'verbose_name_plural': 'Lotes documentales'},
        ),
    ]
