# Generated by Django 5.0 on 2026-06-17 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionConsolidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('total_radian', models.IntegerField(default=0)),
                ('total_correo', models.IntegerField(default=0)),
                ('total_conciliadas', models.IntegerField(default=0)),
                ('total_solo_radian', models.IntegerField(default=0)),
                ('total_solo_correo', models.IntegerField(default=0)),
                ('total_revision', models.IntegerField(default=0)),
                ('error_mensaje', models.TextField(blank=True)),
                ('iniciada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de consolidación',
                'verbose_name_plural': 'Ejecuciones de consolidación',
                'db_table': 'oc_ejecucion',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='FacturaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('cufe', models.CharField(blank=True, db_index=True, max_length=300)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('nit_proveedor', models.CharField(blank=True, max_length=50)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('asunto_correo', models.CharField(max_length=500)),
                ('fecha_correo', models.DateTimeField()),
                ('remitente', models.CharField(max_length=255)),
                ('nombre_remitente', models.CharField(blank=True, max_length=255)),
                ('carpeta', models.CharField(blank=True, max_length=255)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_correo', to='OptimizacionCorreos.ejecucionconsolidacion')),
            ],
            options={
                'verbose_name': 'Factura correo',
                'verbose_name_plural': 'Facturas correo',
                'db_table': 'oc_factura_correo',
            },
        ),
        migrations.CreateModel(
            name='FacturaRadian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('cufe', models.CharField(db_index=True, max_length=300)),
                ('numero', models.CharField(max_length=100)),
                ('nit_proveedor', models.CharField(max_length=50)),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_emision', models.DateField()),
                ('tipo_documento', models.CharField(blank=True, max_length=10)),
                ('track_id', models.CharField(max_length=300)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_radian', to='OptimizacionCorreos.ejecucionconsolidacion')),
            ],
            options={
                'verbose_name': 'Factura RADIAN',
                'verbose_name_plural': 'Facturas RADIAN',
                'db_table': 'oc_factura_radian',
            },
        ),
        migrations.CreateModel(
            name='ResultadoConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('cufe', models.CharField(blank=True, db_index=True, max_length=300)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('nit_proveedor', models.CharField(blank=True, max_length=50)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=255)),
                ('monto_radian', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_correo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('delta_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fecha_radian', models.DateField(blank=True, null=True)),
                ('fecha_correo', models.DateTimeField(blank=True, null=True)),
                ('asunto_correo', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('CONCILIADA', 'Conciliada'), ('REVISION_MANUAL', 'Revisión manual'), ('SOLO_RADIAN', 'Solo RADIAN'), ('SOLO_CORREO', 'Solo correo')], max_length=30)),
                ('nivel_match', models.CharField(blank=True, max_length=5)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='OptimizacionCorreos.ejecucionconsolidacion')),
                ('factura_correo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OptimizacionCorreos.facturacorreo')),
                ('factura_radian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OptimizacionCorreos.facturaradian')),
            ],
            options={
                'verbose_name': 'Resultado de conciliación',
                'verbose_name_plural': 'Resultados de conciliación',
                'db_table': 'oc_resultado',
            },
        ),
    ]
