# Generated by Django 5.0 on 2026-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AusentismoDato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rowid_tnl", models.BigIntegerField(db_index=True, unique=True)),
                ("cedula", models.CharField(db_index=True, max_length=20)),
                ("nombre", models.CharField(max_length=200)),
                ("concepto_id", models.CharField(db_index=True, max_length=20)),
                ("concepto_desc", models.CharField(max_length=200)),
                ("tipo_concepto", models.CharField(blank=True, max_length=20)),
                (
                    "horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "dias",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=200)),
                (
                    "co_codigo",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("mes", models.SmallIntegerField(db_index=True)),
                ("ano", models.SmallIntegerField(db_index=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("sexo", models.CharField(blank=True, max_length=1)),
                ("tipo_contrato", models.CharField(blank=True, max_length=1)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_ausentismo_dato",
                "indexes": [
                    models.Index(
                        fields=["ano", "mes"], name="dashboard_a_ano_73bc69_idx"
                    ),
                    models.Index(
                        fields=["co_codigo", "ano", "mes"],
                        name="dashboard_a_co_codi_f51a37_idx",
                    ),
                    models.Index(
                        fields=["cedula", "ano", "mes"],
                        name="dashboard_a_cedula_eab6a1_idx",
                    ),
                ],
            },
        ),
    ]
