# Generated by Django 5.0 on 2026-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NominaDato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rowid_mv", models.BigIntegerField(db_index=True, unique=True)),
                ("cedula", models.CharField(db_index=True, max_length=20)),
                ("nombre", models.CharField(max_length=200)),
                ("concepto_id", models.CharField(db_index=True, max_length=20)),
                ("concepto_desc", models.CharField(max_length=200)),
                ("naturaleza", models.SmallIntegerField(default=1)),
                (
                    "horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "dias_tnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=200)),
                (
                    "co_codigo",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("co_nombre", models.CharField(blank=True, max_length=100)),
                ("mes", models.SmallIntegerField(db_index=True)),
                ("ano", models.SmallIntegerField(db_index=True)),
                ("es_tnl", models.BooleanField(db_index=True, default=False)),
                ("sexo", models.CharField(blank=True, max_length=1)),
                ("tipo_contrato", models.CharField(blank=True, max_length=1)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_nomina_dato",
                "indexes": [
                    models.Index(
                        fields=["ano", "mes"], name="dashboard_n_ano_a41c49_idx"
                    ),
                    models.Index(
                        fields=["ano", "mes", "co_codigo"],
                        name="dashboard_n_ano_ac0ba1_idx",
                    ),
                    models.Index(
                        fields=["cedula", "ano", "mes"],
                        name="dashboard_n_cedula_ea475d_idx",
                    ),
                    models.Index(
                        fields=["concepto_id", "ano", "mes"],
                        name="dashboard_n_concept_847c41_idx",
                    ),
                ],
            },
        ),
    ]
