# Generated by Django 5.0 on 2026-07-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0002_nominadato"),
    ]

    operations = [
        migrations.CreateModel(
            name="RotacionDato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rowid_contrato", models.BigIntegerField(db_index=True, unique=True)),
                ("cedula", models.CharField(db_index=True, max_length=20)),
                ("nombre", models.CharField(max_length=200)),
                ("cargo", models.CharField(blank=True, max_length=200)),
                (
                    "co_codigo",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("co_nombre", models.CharField(blank=True, max_length=100)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                (
                    "fecha_retiro",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("id_motivo_retiro", models.CharField(blank=True, max_length=10)),
                ("motivo_retiro", models.CharField(blank=True, max_length=200)),
                (
                    "salario",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                (
                    "salario_anterior",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=16, null=True
                    ),
                ),
                ("fecha_contrato_hasta", models.DateField(blank=True, null=True)),
                ("tipo_contrato", models.CharField(blank=True, max_length=1)),
                ("sexo", models.CharField(blank=True, max_length=1)),
                ("es_activo", models.BooleanField(db_index=True, default=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_rotacion_dato",
                "indexes": [
                    models.Index(
                        fields=["es_activo", "co_codigo"],
                        name="dashboard_r_es_acti_5ced93_idx",
                    ),
                    models.Index(
                        fields=["fecha_retiro", "co_codigo"],
                        name="dashboard_r_fecha_r_ef5717_idx",
                    ),
                    models.Index(
                        fields=["cedula", "es_activo"],
                        name="dashboard_r_cedula_2c7675_idx",
                    ),
                ],
            },
        ),
    ]
