# Generated by Django 5.0 on 2026-06-01 19:03

import Usuarios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "cedula",
                    models.CharField(max_length=20, unique=True, verbose_name="Cédula"),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                ("nombres", models.CharField(max_length=80, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=80, verbose_name="Apellidos"),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=Usuarios.models.generar_codigo_unico,
                        editable=False,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "reset_password_token",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "reset_password_token_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "permissions": [
                    ("can_manage_users", "Puede gestionar usuarios"),
                    ("can_manage_roles", "Puede gestionar roles y permisos"),
                    ("can_view_dashboard", "Puede ver el dashboard"),
                    ("can_upload_excel", "Puede subir archivos Excel"),
                    ("can_view_trazabilidad", "Puede ver trazabilidad de empleados"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OTPVerificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                ("codigo", models.CharField(max_length=6, verbose_name="Código OTP")),
                ("expira_en", models.DateTimeField(verbose_name="Expira en")),
                ("usado", models.BooleanField(default=False, verbose_name="Usado")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verificación OTP",
                "verbose_name_plural": "Verificaciones OTP",
                "db_table": "otp_verificaciones",
                "ordering": ["-creado"],
            },
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["correo"], name="usuarios_correo_ee1198_idx"),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["cedula"], name="usuarios_cedula_dd8531_idx"),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["is_active"], name="usuarios_is_acti_8ee55c_idx"
            ),
        ),
    ]
