# Generated by Django 5.0 on 2026-06-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0002_alter_usuario_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "permissions": [
                    ("can_manage_users", "Puede gestionar usuarios"),
                    ("can_manage_roles", "Puede gestionar roles y permisos"),
                    ("can_view_dashboard", "Puede ver el dashboard"),
                    ("can_upload_excel", "Puede subir archivos Excel"),
                    ("can_view_trazabilidad", "Puede ver trazabilidad de empleados"),
                    ("can_manage_sedes", "Puede crear y gestionar sedes"),
                    (
                        "can_manage_cargas",
                        "Puede ver historial de cargas y revertirlas",
                    ),
                ],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
