# Generated by Django 5.0 on 2026-06-04 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0004_origen_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudRecuperacionPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE_OTP", "Pendiente validación OTP"),
                            (
                                "PENDIENTE_ADMIN",
                                "Esperando resolución del administrador",
                            ),
                            ("RESUELTO", "Resuelto"),
                        ],
                        default="PENDIENTE_OTP",
                        max_length=20,
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recuperaciones_resueltas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_recuperacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de recuperación",
                "verbose_name_plural": "Solicitudes de recuperación",
                "db_table": "solicitudes_recuperacion",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="NotificacionAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("recuperacion_password", "Recuperación de contraseña")
                        ],
                        max_length=50,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("cuerpo", models.TextField()),
                ("leida", models.BooleanField(default=False)),
                (
                    "solicitud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="Usuarios.solicitudrecuperacionpassword",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación admin",
                "verbose_name_plural": "Notificaciones admin",
                "db_table": "notificaciones_admin",
                "ordering": ["-creado"],
            },
        ),
    ]
