# Generated by Django 5.0 on 2026-06-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0005_solicitud_recuperacion_notificacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "permissions": [
                    ("can_manage_users", "Puede gestionar usuarios"),
                    ("can_manage_roles", "Puede gestionar roles y permisos"),
                    ("can_view_dashboard", "Puede ver el dashboard"),
                    ("can_upload_excel", "Puede subir archivos Excel"),
                    ("can_view_trazabilidad", "Puede ver trazabilidad de empleados"),
                    ("can_manage_sedes", "Puede gestionar sedes y orígenes de datos"),
                    (
                        "can_edit_registros",
                        "Puede editar estado y proceso de registros de trazabilidad",
                    ),
                    (
                        "can_manage_cargas",
                        "Puede ver historial de cargas y revertirlas",
                    ),
                ],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
