# Generated by Django 5.0 on 2026-06-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0006_historial_cambios_permiso_edit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "permissions": [
                    ("can_manage_users", "Puede gestionar usuarios"),
                    ("can_manage_roles", "Puede gestionar roles y permisos"),
                    ("can_view_dashboard", "Puede ver el dashboard"),
                    ("can_upload_excel", "Puede subir archivos Excel"),
                    ("can_view_trazabilidad", "Puede ver trazabilidad de empleados"),
                    ("can_manage_sedes", "Puede gestionar sedes y orígenes de datos"),
                    (
                        "can_edit_registros",
                        "Puede editar estado y proceso de registros de trazabilidad",
                    ),
                    (
                        "can_manage_cargas",
                        "Puede ver historial de cargas y revertirlas",
                    ),
                    (
                        "can_view_contratos",
                        "Puede ver el panel de contratos y vencimientos",
                    ),
                    (
                        "can_decide_contratos",
                        "Puede tomar decisiones sobre contratos: prorrogar o terminar",
                    ),
                    (
                        "can_escanear_siesa",
                        "Puede ejecutar consulta manual de contratos desde SIESA",
                    ),
                    (
                        "can_manage_asignaciones",
                        "Puede gestionar asignaciones de director/GH a sedes",
                    ),
                ],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
