# Generated by Django 5.0 on 2026-06-10 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0007_add_contratos_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacionadmin",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Si está vacío es una notificación global de admin; si tiene valor es para ese usuario específico.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificaciones_personales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notificacionadmin",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("recuperacion_password", "Recuperación de contraseña"),
                    ("alerta_contrato", "Alerta de contrato"),
                ],
                max_length=50,
            ),
        ),
    ]
