# Generated by Django 5.0 on 2026-06-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contratos", "0002_notificacion_contrato_fk"),
        ("Usuarios", "0009_add_contrataciones_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacionadmin",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notificaciones",
                to="Contratos.contrato",
            ),
        ),
        migrations.AlterField(
            model_name="notificacionadmin",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("recuperacion_password", "Recuperación de contraseña"),
                    ("alerta_contrato", "Alerta de contrato"),
                    ("alerta_urgente", "Alerta urgente de contrato"),
                ],
                max_length=50,
            ),
        ),
    ]
