# Generated by Django 5.0 on 2026-06-01 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                ("nombre", models.CharField(max_length=120, verbose_name="Nombre")),
                ("ciudad", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
            ],
            options={
                "verbose_name": "Sede",
                "verbose_name_plural": "Sedes",
                "db_table": "sedes",
                "ordering": ["ciudad", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CargaExcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                ("nombre_archivo", models.CharField(max_length=250)),
                ("origen_datos", models.CharField(max_length=100)),
                ("total_registros", models.IntegerField(default=0)),
                ("exitosos", models.IntegerField(default=0)),
                ("fallidos", models.IntegerField(default=0)),
                ("errores", models.JSONField(default=list)),
                (
                    "cargado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historial_cargas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargas",
                        to="Trazabilidad.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga de Excel",
                "verbose_name_plural": "Historial de cargas",
                "db_table": "cargas_excel",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="EmpleadoTrazabilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "documento_id",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Número de documento"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        default="CC", max_length=10, verbose_name="Tipo documento"
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(max_length=200, verbose_name="Nombre completo"),
                ),
                (
                    "origen_datos",
                    models.CharField(max_length=100, verbose_name="Origen de datos"),
                ),
                (
                    "estado_candidato",
                    models.CharField(
                        choices=[
                            ("REGISTRADO", "Registrado"),
                            ("HABILITADO", "Habilitado"),
                            ("INHABILITADO", "Inhabilitado"),
                            ("VERIFICACION_PARCIAL", "Verificación parcial"),
                            (
                                "REVISION_MANUAL_AUTORIZADA",
                                "Revisión manual autorizada",
                            ),
                            ("REVISION_MANUAL_RECHAZADA", "Revisión manual rechazada"),
                        ],
                        default="REGISTRADO",
                        max_length=40,
                    ),
                ),
                (
                    "tipo_proceso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SELECCIONADO", "Seleccionado"),
                            ("EMPLEADO", "Empleado"),
                            ("APRENDIZ", "Aprendiz"),
                            ("RETIRADO", "Retirado"),
                            ("CANDIDATO", "Candidato"),
                            ("ENTREVISTADO", "Entrevistado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("motivo_inhabilitacion", models.TextField(blank=True)),
                ("cargo", models.CharField(blank=True, max_length=120)),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("fecha_retiro", models.DateField(blank=True, null=True)),
                ("motivo_retiro", models.CharField(blank=True, max_length=250)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=120)),
                ("direccion", models.CharField(blank=True, max_length=250)),
                ("barrio_municipio", models.CharField(blank=True, max_length=120)),
                ("centro_costos", models.CharField(blank=True, max_length=30)),
                ("eps", models.CharField(blank=True, max_length=100)),
                ("pensiones", models.CharField(blank=True, max_length=100)),
                ("arl", models.CharField(blank=True, max_length=100)),
                ("tipo_sangre", models.CharField(blank=True, max_length=6)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("nivel_escolaridad", models.CharField(blank=True, max_length=60)),
                ("expedida_en", models.CharField(blank=True, max_length=100)),
                ("sexo", models.CharField(blank=True, max_length=10)),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_entrevista", models.DateField(blank=True, null=True)),
                ("psicologa", models.CharField(blank=True, max_length=100)),
                ("fuente_carga", models.CharField(blank=True, max_length=250)),
                (
                    "cargado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleados",
                        to="Trazabilidad.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado / Candidato",
                "verbose_name_plural": "Empleados / Candidatos",
                "db_table": "empleados_trazabilidad",
                "ordering": ["nombre_completo"],
                "indexes": [
                    models.Index(
                        fields=["documento_id"], name="empleados_t_documen_3af4e7_idx"
                    ),
                    models.Index(
                        fields=["origen_datos"], name="empleados_t_origen__12a7fc_idx"
                    ),
                    models.Index(
                        fields=["estado_candidato"],
                        name="empleados_t_estado__a28289_idx",
                    ),
                ],
            },
        ),
    ]
