# Generated by Django 5.0 on 2026-06-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleadotrazabilidad",
            name="carga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="Trazabilidad.cargaexcel",
            ),
        ),
    ]
