# Generated by Django 5.0 on 2026-06-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0002_empleadotrazabilidad_carga"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargaexcel",
            name="hoja",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="empleadotrazabilidad",
            name="tipo_sangre",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
