# Generated by Django 5.0 on 2026-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0003_cargaexcel_hoja_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleadotrazabilidad",
            name="celular",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
