# Generated by Django 5.0 on 2026-06-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0004_celular_max_length_60"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleadotrazabilidad",
            name="tipo_documento",
            field=models.CharField(
                default="CC", max_length=60, verbose_name="Tipo documento"
            ),
        ),
    ]
