# Generated by Django 5.0 on 2026-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0005_tipo_documento_max_length_60"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleadotrazabilidad",
            name="sexo",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
