# Generated by Django 5.0 on 2026-06-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0006_sexo_max_length_30"),
    ]

    operations = [
        migrations.CreateModel(
            name="Origen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Descripción"
                    ),
                ),
            ],
            options={
                "verbose_name": "Origen de datos",
                "verbose_name_plural": "Orígenes de datos",
                "db_table": "origenes_datos",
                "ordering": ["nombre"],
            },
        ),
    ]
