# Generated by Django 5.0 on 2026-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0007_origen_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargaexcel",
            name="firma_gh_cargo",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Cargo firmante GH"
            ),
        ),
        migrations.AddField(
            model_name="cargaexcel",
            name="firma_gh_fecha",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha firma GH"
            ),
        ),
        migrations.AddField(
            model_name="cargaexcel",
            name="firma_gh_imagen",
            field=models.TextField(blank=True, verbose_name="Firma GH (base64 PNG)"),
        ),
        migrations.AddField(
            model_name="cargaexcel",
            name="firma_gh_nombre",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Nombre firmante GH"
            ),
        ),
    ]
