# Generated by Django 5.0 on 2026-06-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0008_firma_gh_carga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleadotrazabilidad",
            name="motivo_retiro",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="empleadotrazabilidad",
            name="tipo_proceso",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELECCIONADO", "Seleccionado"),
                    ("EMPLEADO", "Empleado"),
                    ("APRENDIZ", "Aprendiz"),
                    ("PASANTE", "Pasante"),
                    ("RETIRADO", "Retirado"),
                    ("CANDIDATO", "Candidato"),
                    ("ENTREVISTADO", "Entrevistado"),
                ],
                max_length=30,
            ),
        ),
    ]
