# Generated by Django 5.0 on 2026-06-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0009_motivo_retiro_max_500"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialCambioRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("estado", models.BooleanField(default=True, verbose_name="Estado")),
                (
                    "campo",
                    models.CharField(
                        choices=[
                            ("estado_candidato", "Estado candidato"),
                            ("tipo_proceso", "Tipo de proceso"),
                        ],
                        max_length=30,
                    ),
                ),
                ("valor_anterior", models.CharField(max_length=50)),
                ("valor_nuevo", models.CharField(max_length=50)),
                ("justificacion", models.TextField()),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cambios_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_cambios",
                        to="Trazabilidad.empleadotrazabilidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de cambio",
                "verbose_name_plural": "Historial de cambios",
                "db_table": "historial_cambios_registros",
                "ordering": ["-creado"],
            },
        ),
    ]
