# Generated by Django 5.0 on 2026-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0010_historial_cambios_permiso_edit"),
    ]

    operations = [
        migrations.AddField(
            model_name="sede",
            name="dias_alerta_director",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Días antes del vencimiento del contrato para notificar al director de esta sede",
                verbose_name="Días alerta director",
            ),
        ),
    ]
