# Generated by Django 5.0 on 2026-06-16 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trazabilidad", "0011_sede_dias_alerta_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sede",
            name="dias_alerta_director",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Días antes del vencimiento del contrato para notificar al director de esta sede. Mínimo 5.",
                validators=[django.core.validators.MinValueValidator(5)],
                verbose_name="Días alerta director",
            ),
        ),
    ]
