# Generated by Django 5.0 on 2026-06-10 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Trazabilidad", "0011_sede_dias_alerta_director"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaCarta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NO_PRORROGA", "No prórroga"),
                            ("PRORROGA", "Prórroga"),
                            ("TERMINACION", "Terminación"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plantilla de carta",
                "verbose_name_plural": "Plantillas de carta",
                "db_table": "contratos_plantillas",
            },
        ),
        migrations.CreateModel(
            name="AsignacionCentro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("GH", "Gestión Humana"), ("DIRECTOR", "Director")],
                        max_length=20,
                        verbose_name="Rol en contratos",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_contratos",
                        to="Trazabilidad.sede",
                        verbose_name="Sede",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignacion_centro",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de sede",
                "verbose_name_plural": "Asignaciones de sede",
                "db_table": "contratos_asignaciones_sede",
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_documento", models.CharField(max_length=10)),
                ("documento_id", models.CharField(max_length=30)),
                ("nombre_completo", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=100)),
                ("fecha_inicio_contrato", models.DateField(blank=True, null=True)),
                ("fecha_finalizacion", models.DateField()),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "tipo_carta",
                    models.CharField(
                        choices=[
                            ("NO_PRORROGA", "No prórroga"),
                            ("PRORROGA", "Prórroga"),
                            ("TERMINACION", "Terminación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            (
                                "PENDIENTE_FIRMA_NO_PRORROGA",
                                "Pendiente firma — no prórroga",
                            ),
                            (
                                "PENDIENTE_DECISION_DIRECTOR",
                                "Pendiente decisión director",
                            ),
                            ("PENDIENTE_FIRMA_PRORROGA", "Pendiente firma — prórroga"),
                            (
                                "PENDIENTE_FIRMA_TERMINACION",
                                "Pendiente firma — terminación",
                            ),
                            ("FIRMADO", "Firmado"),
                            ("SIN_CANAL_CONTACTO", "Sin canal de contacto"),
                            ("ERROR_NOTIFICACION", "Error de notificación"),
                        ],
                        default="PENDIENTE_FIRMA_NO_PRORROGA",
                        max_length=40,
                    ),
                ),
                ("token_firma", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("token_usado", models.BooleanField(default=False)),
                ("token_expira_en", models.DateTimeField(blank=True, null=True)),
                ("ip_acceso", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "ip_confirmacion",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("firma_canvas_data", models.TextField(blank=True)),
                ("pdf_carta_key", models.CharField(blank=True, max_length=500)),
                ("pdf_firmado_key", models.CharField(blank=True, max_length=500)),
                (
                    "duracion_prorroga",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3_MESES", "3 meses"),
                            ("6_MESES", "6 meses"),
                            ("12_MESES", "12 meses"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "nuevo_sueldo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("mantener_condiciones", models.BooleanField(default=True)),
                ("fecha_fin_prorroga", models.DateField(blank=True, null=True)),
                ("fecha_primer_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_firma", models.DateTimeField(blank=True, null=True)),
                ("contador_escalamientos", models.PositiveIntegerField(default=0)),
                (
                    "fecha_ultimo_escalamiento",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos",
                        to="Trazabilidad.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "db_table": "contratos_contrato",
                "ordering": ["fecha_finalizacion"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoAdicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("minio_key", models.CharField(max_length=500)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_adicionales",
                        to="Contratos.contrato",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contratos_documentos_adicionales",
            },
        ),
        migrations.CreateModel(
            name="EventoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("GENERADO", "Carta generada"),
                            ("ENVIADO_EMAIL", "Email enviado"),
                            ("ENVIADO_WA", "WhatsApp enviado"),
                            ("ACCESO_FIRMA", "Acceso a firma"),
                            ("FIRMADO", "Firmado"),
                            ("ESCALADO", "Escalado a director"),
                            ("DECISION_DIRECTOR", "Decisión de director"),
                            ("ERROR", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="Contratos.contrato",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contratos_eventos",
                "ordering": ["-timestamp"],
            },
        ),
    ]
