# Generated by Django 5.0 on 2026-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contratos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE_FIRMA_NO_PRORROGA", "Pendiente firma — no prórroga"),
                    ("PENDIENTE_DECISION_DIRECTOR", "Pendiente decisión director"),
                    ("PENDIENTE_FIRMA_PRORROGA", "Pendiente firma — prórroga"),
                    ("PENDIENTE_FIRMA_TERMINACION", "Pendiente firma — terminación"),
                    ("FIRMADO", "Firmado"),
                    ("SIN_CANAL_CONTACTO", "Sin canal de contacto"),
                    ("ERROR_NOTIFICACION", "Error de notificación"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE_FIRMA_NO_PRORROGA",
                max_length=40,
            ),
        ),
    ]
