# Generated by Django 5.0 on 2026-06-11 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contratos", "0002_notificacion_contrato_fk"),
        ("Trazabilidad", "0011_sede_dias_alerta_director"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignacioncentro",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaciones_centro",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asignacioncentro",
            unique_together={("usuario", "sede")},
        ),
    ]
