# Generated by Django 5.0 on 2026-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contratos", "0003_asignacion_fk_multi_sede"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE_FIRMA_NO_PRORROGA", "Pendiente firma — no prórroga"),
                    ("PENDIENTE_DECISION_DIRECTOR", "Pendiente decisión director"),
                    ("PENDIENTE_CONDICIONES_GH", "Pendiente condiciones GH"),
                    (
                        "PENDIENTE_NOTIFICACION_EMPLEADO",
                        "Pendiente notificación empleado",
                    ),
                    ("PENDIENTE_FIRMA_PRORROGA", "Pendiente firma — prórroga"),
                    ("PENDIENTE_FIRMA_TERMINACION", "Pendiente firma — terminación"),
                    ("FIRMADO", "Firmado"),
                    ("SIN_CANAL_CONTACTO", "Sin canal de contacto"),
                    ("ERROR_NOTIFICACION", "Error de notificación"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDIENTE_FIRMA_NO_PRORROGA",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="eventocontrato",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("GENERADO", "Carta generada"),
                    ("ENVIADO_EMAIL", "Email enviado"),
                    ("ENVIADO_WA", "WhatsApp enviado"),
                    ("ACCESO_FIRMA", "Acceso a firma"),
                    ("FIRMADO", "Firmado"),
                    ("ESCALADO", "Escalado a director"),
                    ("DECISION_DIRECTOR", "Decisión de director"),
                    ("CONDICIONES_GH", "Condiciones definidas por GH"),
                    ("NOTIFICACION_EMPLEADO", "Director notificó al empleado"),
                    ("ERROR", "Error"),
                ],
                max_length=30,
            ),
        ),
    ]
