# Generated by Django 5.0 on 2026-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contratos", "0004_alter_contrato_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="no_prorroga_firmada",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="pdf_no_prorroga_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
